// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: rooms/v1/rooms.proto

package rooms_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomService_CreateRoom_FullMethodName                = "/rooms.v1.RoomService/CreateRoom"
	RoomService_GetRoom_FullMethodName                   = "/rooms.v1.RoomService/GetRoom"
	RoomService_UpdateRoom_FullMethodName                = "/rooms.v1.RoomService/UpdateRoom"
	RoomService_DeleteRoom_FullMethodName                = "/rooms.v1.RoomService/DeleteRoom"
	RoomService_ListRooms_FullMethodName                 = "/rooms.v1.RoomService/ListRooms"
	RoomService_EndRoom_FullMethodName                   = "/rooms.v1.RoomService/EndRoom"
	RoomService_AddParticipant_FullMethodName            = "/rooms.v1.RoomService/AddParticipant"
	RoomService_RemoveParticipant_FullMethodName         = "/rooms.v1.RoomService/RemoveParticipant"
	RoomService_GetParticipants_FullMethodName           = "/rooms.v1.RoomService/GetParticipants"
	RoomService_IsParticipant_FullMethodName             = "/rooms.v1.RoomService/IsParticipant"
	RoomService_UpdateParticipantMetadata_FullMethodName = "/rooms.v1.RoomService/UpdateParticipantMetadata"
	RoomService_AssertCanJoin_FullMethodName             = "/rooms.v1.RoomService/AssertCanJoin"
	RoomService_RefreshJoinToken_FullMethodName          = "/rooms.v1.RoomService/RefreshJoinToken"
	RoomService_GetTURNCredentials_FullMethodName        = "/rooms.v1.RoomService/GetTURNCredentials"
)

// RoomServiceClient is the client API for RoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomServiceClient interface {
	// создаёт новую комнату для звонка, возвращает её идентификатор и токен для входа
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	// возвращает информацию о комнате (название, настройки, статус) по её идентификатору
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error)
	// обновляет настройки существующей комнаты (например, меняет название или лимит участников)
	UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*UpdateRoomResponse, error)
	// помечает комнату как удалённую или полностью удаляет её из системы
	DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...grpc.CallOption) (*DeleteRoomResponse, error)
	// возвращает список комнат, созданных пользователем (активных или завершённых)
	ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error)
	// принудительно завершает активную комнату (например, когда все вышли)
	EndRoom(ctx context.Context, in *EndRoomRequest, opts ...grpc.CallOption) (*EndRoomResponse, error)
	// регистрирует вход участника в комнату, проверяет права и возвращает токен для подключения
	AddParticipant(ctx context.Context, in *AddParticipantRequest, opts ...grpc.CallOption) (*AddParticipantResponse, error)
	// фиксирует выход участника из комнаты (добровольный или принудительный)
	RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*RemoveParticipantResponse, error)
	// возвращает список всех активных участников в комнате
	GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error)
	// проверяет, находится ли пользователь в данный момент в комнате
	IsParticipant(ctx context.Context, in *IsParticipantRequest, opts ...grpc.CallOption) (*IsParticipantResponse, error)
	// обновляет дополнительную информацию об участнике (имя, версия клиента, состояние микрофона)
	UpdateParticipantMetadata(ctx context.Context, in *UpdateParticipantMetadataRequest, opts ...grpc.CallOption) (*UpdateParticipantMetadataResponse, error)
	// service-only: room active + user is active participant (signaling/sfu)
	AssertCanJoin(ctx context.Context, in *AssertCanJoinRequest, opts ...grpc.CallOption) (*AssertCanJoinResponse, error)
	// user access JWT: issue a fresh join token for an active participant
	RefreshJoinToken(ctx context.Context, in *RefreshJoinTokenRequest, opts ...grpc.CallOption) (*RefreshJoinTokenResponse, error)
	// ephemeral TURN credentials (HMAC / coturn use-auth-secret)
	GetTURNCredentials(ctx context.Context, in *GetTURNCredentialsRequest, opts ...grpc.CallOption) (*GetTURNCredentialsResponse, error)
}

type roomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomServiceClient(cc grpc.ClientConnInterface) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_GetRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*UpdateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_UpdateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...grpc.CallOption) (*DeleteRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_DeleteRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoomsResponse)
	err := c.cc.Invoke(ctx, RoomService_ListRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) EndRoom(ctx context.Context, in *EndRoomRequest, opts ...grpc.CallOption) (*EndRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndRoomResponse)
	err := c.cc.Invoke(ctx, RoomService_EndRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) AddParticipant(ctx context.Context, in *AddParticipantRequest, opts ...grpc.CallOption) (*AddParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddParticipantResponse)
	err := c.cc.Invoke(ctx, RoomService_AddParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*RemoveParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveParticipantResponse)
	err := c.cc.Invoke(ctx, RoomService_RemoveParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParticipantsResponse)
	err := c.cc.Invoke(ctx, RoomService_GetParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) IsParticipant(ctx context.Context, in *IsParticipantRequest, opts ...grpc.CallOption) (*IsParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsParticipantResponse)
	err := c.cc.Invoke(ctx, RoomService_IsParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) UpdateParticipantMetadata(ctx context.Context, in *UpdateParticipantMetadataRequest, opts ...grpc.CallOption) (*UpdateParticipantMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateParticipantMetadataResponse)
	err := c.cc.Invoke(ctx, RoomService_UpdateParticipantMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) AssertCanJoin(ctx context.Context, in *AssertCanJoinRequest, opts ...grpc.CallOption) (*AssertCanJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssertCanJoinResponse)
	err := c.cc.Invoke(ctx, RoomService_AssertCanJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) RefreshJoinToken(ctx context.Context, in *RefreshJoinTokenRequest, opts ...grpc.CallOption) (*RefreshJoinTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshJoinTokenResponse)
	err := c.cc.Invoke(ctx, RoomService_RefreshJoinToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) GetTURNCredentials(ctx context.Context, in *GetTURNCredentialsRequest, opts ...grpc.CallOption) (*GetTURNCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTURNCredentialsResponse)
	err := c.cc.Invoke(ctx, RoomService_GetTURNCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServiceServer is the server API for RoomService service.
// All implementations must embed UnimplementedRoomServiceServer
// for forward compatibility.
type RoomServiceServer interface {
	// создаёт новую комнату для звонка, возвращает её идентификатор и токен для входа
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	// возвращает информацию о комнате (название, настройки, статус) по её идентификатору
	GetRoom(context.Context, *GetRoomRequest) (*GetRoomResponse, error)
	// обновляет настройки существующей комнаты (например, меняет название или лимит участников)
	UpdateRoom(context.Context, *UpdateRoomRequest) (*UpdateRoomResponse, error)
	// помечает комнату как удалённую или полностью удаляет её из системы
	DeleteRoom(context.Context, *DeleteRoomRequest) (*DeleteRoomResponse, error)
	// возвращает список комнат, созданных пользователем (активных или завершённых)
	ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error)
	// принудительно завершает активную комнату (например, когда все вышли)
	EndRoom(context.Context, *EndRoomRequest) (*EndRoomResponse, error)
	// регистрирует вход участника в комнату, проверяет права и возвращает токен для подключения
	AddParticipant(context.Context, *AddParticipantRequest) (*AddParticipantResponse, error)
	// фиксирует выход участника из комнаты (добровольный или принудительный)
	RemoveParticipant(context.Context, *RemoveParticipantRequest) (*RemoveParticipantResponse, error)
	// возвращает список всех активных участников в комнате
	GetParticipants(context.Context, *GetParticipantsRequest) (*GetParticipantsResponse, error)
	// проверяет, находится ли пользователь в данный момент в комнате
	IsParticipant(context.Context, *IsParticipantRequest) (*IsParticipantResponse, error)
	// обновляет дополнительную информацию об участнике (имя, версия клиента, состояние микрофона)
	UpdateParticipantMetadata(context.Context, *UpdateParticipantMetadataRequest) (*UpdateParticipantMetadataResponse, error)
	// service-only: room active + user is active participant (signaling/sfu)
	AssertCanJoin(context.Context, *AssertCanJoinRequest) (*AssertCanJoinResponse, error)
	// user access JWT: issue a fresh join token for an active participant
	RefreshJoinToken(context.Context, *RefreshJoinTokenRequest) (*RefreshJoinTokenResponse, error)
	// ephemeral TURN credentials (HMAC / coturn use-auth-secret)
	GetTURNCredentials(context.Context, *GetTURNCredentialsRequest) (*GetTURNCredentialsResponse, error)
	mustEmbedUnimplementedRoomServiceServer()
}

// UnimplementedRoomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomServiceServer struct{}

func (UnimplementedRoomServiceServer) CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedRoomServiceServer) GetRoom(context.Context, *GetRoomRequest) (*GetRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoom not implemented")
}
func (UnimplementedRoomServiceServer) UpdateRoom(context.Context, *UpdateRoomRequest) (*UpdateRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoom not implemented")
}
func (UnimplementedRoomServiceServer) DeleteRoom(context.Context, *DeleteRoomRequest) (*DeleteRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoom not implemented")
}
func (UnimplementedRoomServiceServer) ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRooms not implemented")
}
func (UnimplementedRoomServiceServer) EndRoom(context.Context, *EndRoomRequest) (*EndRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndRoom not implemented")
}
func (UnimplementedRoomServiceServer) AddParticipant(context.Context, *AddParticipantRequest) (*AddParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddParticipant not implemented")
}
func (UnimplementedRoomServiceServer) RemoveParticipant(context.Context, *RemoveParticipantRequest) (*RemoveParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveParticipant not implemented")
}
func (UnimplementedRoomServiceServer) GetParticipants(context.Context, *GetParticipantsRequest) (*GetParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipants not implemented")
}
func (UnimplementedRoomServiceServer) IsParticipant(context.Context, *IsParticipantRequest) (*IsParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsParticipant not implemented")
}
func (UnimplementedRoomServiceServer) UpdateParticipantMetadata(context.Context, *UpdateParticipantMetadataRequest) (*UpdateParticipantMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParticipantMetadata not implemented")
}
func (UnimplementedRoomServiceServer) AssertCanJoin(context.Context, *AssertCanJoinRequest) (*AssertCanJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssertCanJoin not implemented")
}
func (UnimplementedRoomServiceServer) RefreshJoinToken(context.Context, *RefreshJoinTokenRequest) (*RefreshJoinTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshJoinToken not implemented")
}
func (UnimplementedRoomServiceServer) GetTURNCredentials(context.Context, *GetTURNCredentialsRequest) (*GetTURNCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTURNCredentials not implemented")
}
func (UnimplementedRoomServiceServer) mustEmbedUnimplementedRoomServiceServer() {}
func (UnimplementedRoomServiceServer) testEmbeddedByValue()                     {}

// UnsafeRoomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomServiceServer will
// result in compilation errors.
type UnsafeRoomServiceServer interface {
	mustEmbedUnimplementedRoomServiceServer()
}

func RegisterRoomServiceServer(s grpc.ServiceRegistrar, srv RoomServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomService_ServiceDesc, srv)
}

func _RoomService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_GetRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_UpdateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).UpdateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_UpdateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).UpdateRoom(ctx, req.(*UpdateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_DeleteRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).DeleteRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_DeleteRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).DeleteRoom(ctx, req.(*DeleteRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_ListRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).ListRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_ListRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).ListRooms(ctx, req.(*ListRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_EndRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).EndRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_EndRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).EndRoom(ctx, req.(*EndRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_AddParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).AddParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_AddParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).AddParticipant(ctx, req.(*AddParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_RemoveParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).RemoveParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_RemoveParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).RemoveParticipant(ctx, req.(*RemoveParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_GetParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).GetParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_GetParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).GetParticipants(ctx, req.(*GetParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_IsParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).IsParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_IsParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).IsParticipant(ctx, req.(*IsParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_UpdateParticipantMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParticipantMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).UpdateParticipantMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_UpdateParticipantMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).UpdateParticipantMetadata(ctx, req.(*UpdateParticipantMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_AssertCanJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssertCanJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).AssertCanJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_AssertCanJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).AssertCanJoin(ctx, req.(*AssertCanJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_RefreshJoinToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshJoinTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).RefreshJoinToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_RefreshJoinToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).RefreshJoinToken(ctx, req.(*RefreshJoinTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_GetTURNCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTURNCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).GetTURNCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomService_GetTURNCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).GetTURNCredentials(ctx, req.(*GetTURNCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomService_ServiceDesc is the grpc.ServiceDesc for RoomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rooms.v1.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomService_CreateRoom_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _RoomService_GetRoom_Handler,
		},
		{
			MethodName: "UpdateRoom",
			Handler:    _RoomService_UpdateRoom_Handler,
		},
		{
			MethodName: "DeleteRoom",
			Handler:    _RoomService_DeleteRoom_Handler,
		},
		{
			MethodName: "ListRooms",
			Handler:    _RoomService_ListRooms_Handler,
		},
		{
			MethodName: "EndRoom",
			Handler:    _RoomService_EndRoom_Handler,
		},
		{
			MethodName: "AddParticipant",
			Handler:    _RoomService_AddParticipant_Handler,
		},
		{
			MethodName: "RemoveParticipant",
			Handler:    _RoomService_RemoveParticipant_Handler,
		},
		{
			MethodName: "GetParticipants",
			Handler:    _RoomService_GetParticipants_Handler,
		},
		{
			MethodName: "IsParticipant",
			Handler:    _RoomService_IsParticipant_Handler,
		},
		{
			MethodName: "UpdateParticipantMetadata",
			Handler:    _RoomService_UpdateParticipantMetadata_Handler,
		},
		{
			MethodName: "AssertCanJoin",
			Handler:    _RoomService_AssertCanJoin_Handler,
		},
		{
			MethodName: "RefreshJoinToken",
			Handler:    _RoomService_RefreshJoinToken_Handler,
		},
		{
			MethodName: "GetTURNCredentials",
			Handler:    _RoomService_GetTURNCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rooms/v1/rooms.proto",
}
