// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: rooms/v1/rooms.proto

package rooms_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Настройки комнаты
type RoomSettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxParticipants  int32                  `protobuf:"varint,1,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`    // максимальное количество участников
	AllowedUsers     []string               `protobuf:"bytes,3,rep,name=allowed_users,json=allowedUsers,proto3" json:"allowed_users,omitempty"`              // список пользователей, допущенных в приватную комнату (пустой = публичная)
	Quality          string                 `protobuf:"bytes,4,opt,name=quality,proto3" json:"quality,omitempty"`                                            // качество видео
	AutoClose        bool                   `protobuf:"varint,5,opt,name=auto_close,json=autoClose,proto3" json:"auto_close,omitempty"`                      // автоматически завершать комнату, когда все вышли
	RecordingEnabled bool                   `protobuf:"varint,6,opt,name=recording_enabled,json=recordingEnabled,proto3" json:"recording_enabled,omitempty"` // включить запись звонка (SFU egress)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RoomSettings) Reset() {
	*x = RoomSettings{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSettings) ProtoMessage() {}

func (x *RoomSettings) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSettings.ProtoReflect.Descriptor instead.
func (*RoomSettings) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{0}
}

func (x *RoomSettings) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *RoomSettings) GetAllowedUsers() []string {
	if x != nil {
		return x.AllowedUsers
	}
	return nil
}

func (x *RoomSettings) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *RoomSettings) GetAutoClose() bool {
	if x != nil {
		return x.AutoClose
	}
	return false
}

func (x *RoomSettings) GetRecordingEnabled() bool {
	if x != nil {
		return x.RecordingEnabled
	}
	return false
}

// Полная информация о комнате
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`             // уникальный идентификатор комнаты (UUID)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                     // название комнаты
	OwnerUuid     string                 `protobuf:"bytes,3,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`          // кто создал комнату
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // время создания
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // время последнего обновления
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`          // время удаления (если есть)
	RoomSettings  *RoomSettings          `protobuf:"bytes,7,opt,name=room_settings,json=roomSettings,proto3" json:"room_settings,omitempty"` // настройки комнаты (метаданные)
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                                 // статуc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Room) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Room) GetRoomSettings() *RoomSettings {
	if x != nil {
		return x.RoomSettings
	}
	return nil
}

func (x *Room) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Запрос на создание комнаты
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                     // название комнаты
	OwnerUuid     string                 `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`          // идентификатор создателя (из JWT)
	RoomSettings  *RoomSettings          `protobuf:"bytes,3,opt,name=room_settings,json=roomSettings,proto3" json:"room_settings,omitempty"` // настройки комнаты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *CreateRoomRequest) GetRoomSettings() *RoomSettings {
	if x != nil {
		return x.RoomSettings
	}
	return nil
}

// Ответ о создании комнаты, включающий в себя структуру room и токен
type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`                            // созданная комната со всеми полями
	JoinToken     string                 `protobuf:"bytes,2,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"` // JWT для немедленного подключения к signaling
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *CreateRoomResponse) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

// Запрос на получение UUID комнаты
type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"` // идентификатор комнаты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoomRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

// Ответ с информацией о комнате в структуре room
type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"` // информация о комнате
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Запрос на обновление комнаты
type UpdateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`             // идентификатор комнаты
	OwnerUuid     string                 `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`          // идентификатор владельца (для проверки прав)
	RoomSettings  *RoomSettings          `protobuf:"bytes,3,opt,name=room_settings,json=roomSettings,proto3" json:"room_settings,omitempty"` // новые настройки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoomRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *UpdateRoomRequest) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *UpdateRoomRequest) GetRoomSettings() *RoomSettings {
	if x != nil {
		return x.RoomSettings
	}
	return nil
}

// Ответ на запрос обновления комнаты с флагом успеха и новой структурой комнаты
type UpdateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // успешно ли обновление
	Room          *Room                  `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`        // обновлённая комната
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomResponse) Reset() {
	*x = UpdateRoomResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomResponse) ProtoMessage() {}

func (x *UpdateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Запрос на удаление комнаты
type DeleteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`    // идентификатор комнаты
	OwnerUuid     string                 `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"` // идентификатор владельца (для проверки прав)
	Permanent     bool                   `protobuf:"varint,3,opt,name=permanent,proto3" json:"permanent,omitempty"`                 // true = полное удаление, false = soft delete (мягкое удаление, это когда мы не удаляем а просто ставим время удаления, что бы могли обратиться к комнате в будущем)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoomRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *DeleteRoomRequest) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *DeleteRoomRequest) GetPermanent() bool {
	if x != nil {
		return x.Permanent
	}
	return false
}

// Ответ на запрос удаления комнаты
// Ответ на запрос о удалении комнаты содержащий флаг успеха
type DeleteRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // успешно ли удаление
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomResponse) Reset() {
	*x = DeleteRoomResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomResponse) ProtoMessage() {}

func (x *DeleteRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на получение списка комнат пользователя с поддержкой фильтрации и пагинации
type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerUuid     string                 `protobuf:"bytes,1,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"` // чьи комнаты ищем
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // фильтр по статусу: "active", "ended", "all"
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                         // количество записей (пагинация)
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                       // смещение (пагинация)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoomsRequest) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *ListRoomsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRoomsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRoomsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Ответ со списком комнат и общим количеством для пагинации
type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`  // список комнат
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // общее количество (для пагинации)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{11}
}

func (x *ListRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *ListRoomsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Запрос на принудительное завершение активной комнаты
type EndRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`    // идентификатор комнаты
	OwnerUuid     string                 `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"` // идентификатор владельца или модератора
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndRoomRequest) Reset() {
	*x = EndRoomRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRoomRequest) ProtoMessage() {}

func (x *EndRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRoomRequest.ProtoReflect.Descriptor instead.
func (*EndRoomRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{12}
}

func (x *EndRoomRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *EndRoomRequest) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

// Ответ на запрос завершения комнаты
type EndRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // успешно ли завершение
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndRoomResponse) Reset() {
	*x = EndRoomResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRoomResponse) ProtoMessage() {}

func (x *EndRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRoomResponse.ProtoReflect.Descriptor instead.
func (*EndRoomResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{13}
}

func (x *EndRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Информация об участнике
type Participant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"` // идентификатор участника
	RoomUuid      string                 `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"` // комната, в которой участвует
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"` // время входа
	LeftAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`       // время выхода (если вышел)
	Metadata      *ParticipantMetadata   `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`                 // метаданные в JSON (имя, клиент, состояние)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{14}
}

func (x *Participant) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *Participant) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *Participant) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *Participant) GetLeftAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeftAt
	}
	return nil
}

func (x *Participant) GetMetadata() *ParticipantMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Метаданные участника (для удобства, но в proto храним как отдельный месседж)
type ParticipantMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`       // отображаемое имя
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`             // информация о клиенте
	ClientVersion string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // версия клиента
	AudioMuted    bool                   `protobuf:"varint,4,opt,name=audio_muted,json=audioMuted,proto3" json:"audio_muted,omitempty"`         // заглушен ли микрофон
	VideoMuted    bool                   `protobuf:"varint,5,opt,name=video_muted,json=videoMuted,proto3" json:"video_muted,omitempty"`         // выключена ли камера
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`                                        // роль: "participant", "moderator", "owner"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantMetadata) Reset() {
	*x = ParticipantMetadata{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantMetadata) ProtoMessage() {}

func (x *ParticipantMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantMetadata.ProtoReflect.Descriptor instead.
func (*ParticipantMetadata) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{15}
}

func (x *ParticipantMetadata) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ParticipantMetadata) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ParticipantMetadata) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ParticipantMetadata) GetAudioMuted() bool {
	if x != nil {
		return x.AudioMuted
	}
	return false
}

func (x *ParticipantMetadata) GetVideoMuted() bool {
	if x != nil {
		return x.VideoMuted
	}
	return false
}

func (x *ParticipantMetadata) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// Запрос на добавление участника в комнату
type AddParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"` // в какую комнату входит
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"` // кто входит
	Metadata      *ParticipantMetadata   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`                 // дополнительная информация (имя, браузер и т.п.) в JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParticipantRequest) Reset() {
	*x = AddParticipantRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantRequest) ProtoMessage() {}

func (x *AddParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantRequest.ProtoReflect.Descriptor instead.
func (*AddParticipantRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{16}
}

func (x *AddParticipantRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *AddParticipantRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *AddParticipantRequest) GetMetadata() *ParticipantMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Ответ на запрос добавления участника в комнату
type AddParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                     // успешно ли добавлен участник
	JoinToken     string                 `protobuf:"bytes,2,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"` // JWT для подключения к signaling сервису
	Participant   *Participant           `protobuf:"bytes,3,opt,name=participant,proto3" json:"participant,omitempty"`              // информация о добавленном участнике
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParticipantResponse) Reset() {
	*x = AddParticipantResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantResponse) ProtoMessage() {}

func (x *AddParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantResponse.ProtoReflect.Descriptor instead.
func (*AddParticipantResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{17}
}

func (x *AddParticipantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddParticipantResponse) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *AddParticipantResponse) GetParticipant() *Participant {
	if x != nil {
		return x.Participant
	}
	return nil
}

// Запрос на удаление участника из комнаты (выход или кик)
type RemoveParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`    // из какой комнаты выходит
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`    // кто выходит
	RemovedBy     string                 `protobuf:"bytes,3,opt,name=removed_by,json=removedBy,proto3" json:"removed_by,omitempty"` // кто инициировал удаление (для кика)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantRequest) Reset() {
	*x = RemoveParticipantRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantRequest) ProtoMessage() {}

func (x *RemoveParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantRequest.ProtoReflect.Descriptor instead.
func (*RemoveParticipantRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveParticipantRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *RemoveParticipantRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *RemoveParticipantRequest) GetRemovedBy() string {
	if x != nil {
		return x.RemovedBy
	}
	return ""
}

// Ответ на запрос удаления участника из комнаты
type RemoveParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // успешно ли удаление
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantResponse) Reset() {
	*x = RemoveParticipantResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantResponse) ProtoMessage() {}

func (x *RemoveParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantResponse.ProtoReflect.Descriptor instead.
func (*RemoveParticipantResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveParticipantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на получение списка участников комнаты
type GetParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`        // комната
	OnlyActive    bool                   `protobuf:"varint,2,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"` // только активные (не вышедшие)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsRequest) Reset() {
	*x = GetParticipantsRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsRequest) ProtoMessage() {}

func (x *GetParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{20}
}

func (x *GetParticipantsRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *GetParticipantsRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

// Ответ со списком участников комнаты и количеством активных
type GetParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*Participant         `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`                   // список участников
	ActiveCount   int32                  `protobuf:"varint,2,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"` // количество активных
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsResponse) Reset() {
	*x = GetParticipantsResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsResponse) ProtoMessage() {}

func (x *GetParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{21}
}

func (x *GetParticipantsResponse) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *GetParticipantsResponse) GetActiveCount() int32 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

// Запрос на проверку, активен ли участник в комнате
type IsParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"` // комната
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"` // пользователь
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsParticipantRequest) Reset() {
	*x = IsParticipantRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsParticipantRequest) ProtoMessage() {}

func (x *IsParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsParticipantRequest.ProtoReflect.Descriptor instead.
func (*IsParticipantRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{22}
}

func (x *IsParticipantRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *IsParticipantRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// Ответ на запрос проверки активности участника в комнате
type IsParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` // true если активен в комнате
	Participant   *Participant           `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"`            // информация об участнике (если активен)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsParticipantResponse) Reset() {
	*x = IsParticipantResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsParticipantResponse) ProtoMessage() {}

func (x *IsParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsParticipantResponse.ProtoReflect.Descriptor instead.
func (*IsParticipantResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{23}
}

func (x *IsParticipantResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *IsParticipantResponse) GetParticipant() *Participant {
	if x != nil {
		return x.Participant
	}
	return nil
}

// Запрос на обновление метаданных участника в комнате
type UpdateParticipantMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"` // комната
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"` // пользователь
	Metadata      *ParticipantMetadata   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`                 // новые метаданные в JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParticipantMetadataRequest) Reset() {
	*x = UpdateParticipantMetadataRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParticipantMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParticipantMetadataRequest) ProtoMessage() {}

func (x *UpdateParticipantMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParticipantMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateParticipantMetadataRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateParticipantMetadataRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *UpdateParticipantMetadataRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateParticipantMetadataRequest) GetMetadata() *ParticipantMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Ответ на запрос обновления метаданных участника
type UpdateParticipantMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`        // успешно ли обновление
	Participant   *Participant           `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"` // обновлённый участник
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParticipantMetadataResponse) Reset() {
	*x = UpdateParticipantMetadataResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParticipantMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParticipantMetadataResponse) ProtoMessage() {}

func (x *UpdateParticipantMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParticipantMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateParticipantMetadataResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateParticipantMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateParticipantMetadataResponse) GetParticipant() *Participant {
	if x != nil {
		return x.Participant
	}
	return nil
}

// AssertCanJoinRequest is used by signaling/sfu (service JWT) to verify join eligibility.
type AssertCanJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertCanJoinRequest) Reset() {
	*x = AssertCanJoinRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertCanJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertCanJoinRequest) ProtoMessage() {}

func (x *AssertCanJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertCanJoinRequest.ProtoReflect.Descriptor instead.
func (*AssertCanJoinRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{26}
}

func (x *AssertCanJoinRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *AssertCanJoinRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// AssertCanJoinResponse reports whether the user may join the room.
type AssertCanJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RoomStatus    string                 `protobuf:"bytes,2,opt,name=room_status,json=roomStatus,proto3" json:"room_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertCanJoinResponse) Reset() {
	*x = AssertCanJoinResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertCanJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertCanJoinResponse) ProtoMessage() {}

func (x *AssertCanJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertCanJoinResponse.ProtoReflect.Descriptor instead.
func (*AssertCanJoinResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{27}
}

func (x *AssertCanJoinResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AssertCanJoinResponse) GetRoomStatus() string {
	if x != nil {
		return x.RoomStatus
	}
	return ""
}

// RefreshJoinTokenRequest asks for a new join JWT for an active participant.
type RefreshJoinTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshJoinTokenRequest) Reset() {
	*x = RefreshJoinTokenRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshJoinTokenRequest) ProtoMessage() {}

func (x *RefreshJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{28}
}

func (x *RefreshJoinTokenRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *RefreshJoinTokenRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// RefreshJoinTokenResponse contains a freshly issued join JWT.
type RefreshJoinTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshJoinTokenResponse) Reset() {
	*x = RefreshJoinTokenResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshJoinTokenResponse) ProtoMessage() {}

func (x *RefreshJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{29}
}

func (x *RefreshJoinTokenResponse) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

// GetTURNCredentialsRequest requests short-lived TURN credentials for a participant.
type GetTURNCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTURNCredentialsRequest) Reset() {
	*x = GetTURNCredentialsRequest{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTURNCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTURNCredentialsRequest) ProtoMessage() {}

func (x *GetTURNCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTURNCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetTURNCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{30}
}

func (x *GetTURNCredentialsRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *GetTURNCredentialsRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// ICEServer describes a STUN/TURN endpoint with optional credentials.
type ICEServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Credential    string                 `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICEServer) Reset() {
	*x = ICEServer{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICEServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICEServer) ProtoMessage() {}

func (x *ICEServer) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICEServer.ProtoReflect.Descriptor instead.
func (*ICEServer) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{31}
}

func (x *ICEServer) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ICEServer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ICEServer) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

// GetTURNCredentialsResponse returns ICE servers with ephemeral TURN credentials.
type GetTURNCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IceServers    []*ICEServer           `protobuf:"bytes,1,rep,name=ice_servers,json=iceServers,proto3" json:"ice_servers,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTURNCredentialsResponse) Reset() {
	*x = GetTURNCredentialsResponse{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTURNCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTURNCredentialsResponse) ProtoMessage() {}

func (x *GetTURNCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTURNCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetTURNCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{32}
}

func (x *GetTURNCredentialsResponse) GetIceServers() []*ICEServer {
	if x != nil {
		return x.IceServers
	}
	return nil
}

func (x *GetTURNCredentialsResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// Структура описания ошибки, которую может вернуть сервис
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // код ошибки (например, "ROOM_NOT_FOUND")
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // человекочитаемое описание
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{33}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Структура общего статуса операции, включающая успех и возможную ошибку
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // успех операции
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // дополнительное сообщение
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // ошибка (если есть)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_rooms_v1_rooms_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_v1_rooms_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_rooms_v1_rooms_proto_rawDescGZIP(), []int{34}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_rooms_v1_rooms_proto protoreflect.FileDescriptor

const file_rooms_v1_rooms_proto_rawDesc = "" +
	"\n" +
	"\x14rooms/v1/rooms.proto\x12\brooms.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x01\n" +
	"\fRoomSettings\x12)\n" +
	"\x10max_participants\x18\x01 \x01(\x05R\x0fmaxParticipants\x12#\n" +
	"\rallowed_users\x18\x03 \x03(\tR\fallowedUsers\x12\x18\n" +
	"\aquality\x18\x04 \x01(\tR\aquality\x12\x1d\n" +
	"\n" +
	"auto_close\x18\x05 \x01(\bR\tautoClose\x12+\n" +
	"\x11recording_enabled\x18\x06 \x01(\bR\x10recordingEnabled\"\xdc\x02\n" +
	"\x04Room\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x03 \x01(\tR\townerUuid\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12;\n" +
	"\rroom_settings\x18\a \x01(\v2\x16.rooms.v1.RoomSettingsR\froomSettings\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\x83\x01\n" +
	"\x11CreateRoomRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x02 \x01(\tR\townerUuid\x12;\n" +
	"\rroom_settings\x18\x03 \x01(\v2\x16.rooms.v1.RoomSettingsR\froomSettings\"W\n" +
	"\x12CreateRoomResponse\x12\"\n" +
	"\x04room\x18\x01 \x01(\v2\x0e.rooms.v1.RoomR\x04room\x12\x1d\n" +
	"\n" +
	"join_token\x18\x02 \x01(\tR\tjoinToken\"-\n" +
	"\x0eGetRoomRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\"5\n" +
	"\x0fGetRoomResponse\x12\"\n" +
	"\x04room\x18\x01 \x01(\v2\x0e.rooms.v1.RoomR\x04room\"\x8c\x01\n" +
	"\x11UpdateRoomRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x02 \x01(\tR\townerUuid\x12;\n" +
	"\rroom_settings\x18\x03 \x01(\v2\x16.rooms.v1.RoomSettingsR\froomSettings\"R\n" +
	"\x12UpdateRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\x04room\x18\x02 \x01(\v2\x0e.rooms.v1.RoomR\x04room\"m\n" +
	"\x11DeleteRoomRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x02 \x01(\tR\townerUuid\x12\x1c\n" +
	"\tpermanent\x18\x03 \x01(\bR\tpermanent\".\n" +
	"\x12DeleteRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"w\n" +
	"\x10ListRoomsRequest\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x01 \x01(\tR\townerUuid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"O\n" +
	"\x11ListRoomsResponse\x12$\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0e.rooms.v1.RoomR\x05rooms\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"L\n" +
	"\x0eEndRoomRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x02 \x01(\tR\townerUuid\"+\n" +
	"\x0fEndRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf0\x01\n" +
	"\vParticipant\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x1b\n" +
	"\troom_uuid\x18\x02 \x01(\tR\broomUuid\x127\n" +
	"\tjoined_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x123\n" +
	"\aleft_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06leftAt\x129\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1d.rooms.v1.ParticipantMetadataR\bmetadata\"\xd4\x01\n" +
	"\x13ParticipantMetadata\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x12\x1f\n" +
	"\vaudio_muted\x18\x04 \x01(\bR\n" +
	"audioMuted\x12\x1f\n" +
	"\vvideo_muted\x18\x05 \x01(\bR\n" +
	"videoMuted\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\"\x8c\x01\n" +
	"\x15AddParticipantRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x129\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1d.rooms.v1.ParticipantMetadataR\bmetadata\"\x8a\x01\n" +
	"\x16AddParticipantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"join_token\x18\x02 \x01(\tR\tjoinToken\x127\n" +
	"\vparticipant\x18\x03 \x01(\v2\x15.rooms.v1.ParticipantR\vparticipant\"s\n" +
	"\x18RemoveParticipantRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x1d\n" +
	"\n" +
	"removed_by\x18\x03 \x01(\tR\tremovedBy\"5\n" +
	"\x19RemoveParticipantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x16GetParticipantsRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1f\n" +
	"\vonly_active\x18\x02 \x01(\bR\n" +
	"onlyActive\"w\n" +
	"\x17GetParticipantsResponse\x129\n" +
	"\fparticipants\x18\x01 \x03(\v2\x15.rooms.v1.ParticipantR\fparticipants\x12!\n" +
	"\factive_count\x18\x02 \x01(\x05R\vactiveCount\"P\n" +
	"\x14IsParticipantRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\"m\n" +
	"\x15IsParticipantResponse\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x127\n" +
	"\vparticipant\x18\x02 \x01(\v2\x15.rooms.v1.ParticipantR\vparticipant\"\x97\x01\n" +
	" UpdateParticipantMetadataRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x129\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1d.rooms.v1.ParticipantMetadataR\bmetadata\"v\n" +
	"!UpdateParticipantMetadataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\vparticipant\x18\x02 \x01(\v2\x15.rooms.v1.ParticipantR\vparticipant\"P\n" +
	"\x14AssertCanJoinRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\"H\n" +
	"\x15AssertCanJoinResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vroom_status\x18\x02 \x01(\tR\n" +
	"roomStatus\"S\n" +
	"\x17RefreshJoinTokenRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\"9\n" +
	"\x18RefreshJoinTokenResponse\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\"U\n" +
	"\x19GetTURNCredentialsRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\"[\n" +
	"\tICEServer\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"credential\x18\x03 \x01(\tR\n" +
	"credential\"s\n" +
	"\x1aGetTURNCredentialsResponse\x124\n" +
	"\vice_servers\x18\x01 \x03(\v2\x13.rooms.v1.ICEServerR\n" +
	"iceServers\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x05error\x18\x03 \x01(\v2\x0f.rooms.v1.ErrorR\x05error2\x8f\t\n" +
	"\vRoomService\x12G\n" +
	"\n" +
	"CreateRoom\x12\x1b.rooms.v1.CreateRoomRequest\x1a\x1c.rooms.v1.CreateRoomResponse\x12>\n" +
	"\aGetRoom\x12\x18.rooms.v1.GetRoomRequest\x1a\x19.rooms.v1.GetRoomResponse\x12G\n" +
	"\n" +
	"UpdateRoom\x12\x1b.rooms.v1.UpdateRoomRequest\x1a\x1c.rooms.v1.UpdateRoomResponse\x12G\n" +
	"\n" +
	"DeleteRoom\x12\x1b.rooms.v1.DeleteRoomRequest\x1a\x1c.rooms.v1.DeleteRoomResponse\x12D\n" +
	"\tListRooms\x12\x1a.rooms.v1.ListRoomsRequest\x1a\x1b.rooms.v1.ListRoomsResponse\x12>\n" +
	"\aEndRoom\x12\x18.rooms.v1.EndRoomRequest\x1a\x19.rooms.v1.EndRoomResponse\x12S\n" +
	"\x0eAddParticipant\x12\x1f.rooms.v1.AddParticipantRequest\x1a .rooms.v1.AddParticipantResponse\x12\\\n" +
	"\x11RemoveParticipant\x12\".rooms.v1.RemoveParticipantRequest\x1a#.rooms.v1.RemoveParticipantResponse\x12V\n" +
	"\x0fGetParticipants\x12 .rooms.v1.GetParticipantsRequest\x1a!.rooms.v1.GetParticipantsResponse\x12P\n" +
	"\rIsParticipant\x12\x1e.rooms.v1.IsParticipantRequest\x1a\x1f.rooms.v1.IsParticipantResponse\x12t\n" +
	"\x19UpdateParticipantMetadata\x12*.rooms.v1.UpdateParticipantMetadataRequest\x1a+.rooms.v1.UpdateParticipantMetadataResponse\x12P\n" +
	"\rAssertCanJoin\x12\x1e.rooms.v1.AssertCanJoinRequest\x1a\x1f.rooms.v1.AssertCanJoinResponse\x12Y\n" +
	"\x10RefreshJoinToken\x12!.rooms.v1.RefreshJoinTokenRequest\x1a\".rooms.v1.RefreshJoinTokenResponse\x12_\n" +
	"\x12GetTURNCredentials\x12#.rooms.v1.GetTURNCredentialsRequest\x1a$.rooms.v1.GetTURNCredentialsResponseBOZMgithub.com/CARAI-REA/messanger/callService/shared/pkg/proto/rooms/v1;rooms_v1b\x06proto3"

var (
	file_rooms_v1_rooms_proto_rawDescOnce sync.Once
	file_rooms_v1_rooms_proto_rawDescData []byte
)

func file_rooms_v1_rooms_proto_rawDescGZIP() []byte {
	file_rooms_v1_rooms_proto_rawDescOnce.Do(func() {
		file_rooms_v1_rooms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rooms_v1_rooms_proto_rawDesc), len(file_rooms_v1_rooms_proto_rawDesc)))
	})
	return file_rooms_v1_rooms_proto_rawDescData
}

var file_rooms_v1_rooms_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_rooms_v1_rooms_proto_goTypes = []any{
	(*RoomSettings)(nil),                      // 0: rooms.v1.RoomSettings
	(*Room)(nil),                              // 1: rooms.v1.Room
	(*CreateRoomRequest)(nil),                 // 2: rooms.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),                // 3: rooms.v1.CreateRoomResponse
	(*GetRoomRequest)(nil),                    // 4: rooms.v1.GetRoomRequest
	(*GetRoomResponse)(nil),                   // 5: rooms.v1.GetRoomResponse
	(*UpdateRoomRequest)(nil),                 // 6: rooms.v1.UpdateRoomRequest
	(*UpdateRoomResponse)(nil),                // 7: rooms.v1.UpdateRoomResponse
	(*DeleteRoomRequest)(nil),                 // 8: rooms.v1.DeleteRoomRequest
	(*DeleteRoomResponse)(nil),                // 9: rooms.v1.DeleteRoomResponse
	(*ListRoomsRequest)(nil),                  // 10: rooms.v1.ListRoomsRequest
	(*ListRoomsResponse)(nil),                 // 11: rooms.v1.ListRoomsResponse
	(*EndRoomRequest)(nil),                    // 12: rooms.v1.EndRoomRequest
	(*EndRoomResponse)(nil),                   // 13: rooms.v1.EndRoomResponse
	(*Participant)(nil),                       // 14: rooms.v1.Participant
	(*ParticipantMetadata)(nil),               // 15: rooms.v1.ParticipantMetadata
	(*AddParticipantRequest)(nil),             // 16: rooms.v1.AddParticipantRequest
	(*AddParticipantResponse)(nil),            // 17: rooms.v1.AddParticipantResponse
	(*RemoveParticipantRequest)(nil),          // 18: rooms.v1.RemoveParticipantRequest
	(*RemoveParticipantResponse)(nil),         // 19: rooms.v1.RemoveParticipantResponse
	(*GetParticipantsRequest)(nil),            // 20: rooms.v1.GetParticipantsRequest
	(*GetParticipantsResponse)(nil),           // 21: rooms.v1.GetParticipantsResponse
	(*IsParticipantRequest)(nil),              // 22: rooms.v1.IsParticipantRequest
	(*IsParticipantResponse)(nil),             // 23: rooms.v1.IsParticipantResponse
	(*UpdateParticipantMetadataRequest)(nil),  // 24: rooms.v1.UpdateParticipantMetadataRequest
	(*UpdateParticipantMetadataResponse)(nil), // 25: rooms.v1.UpdateParticipantMetadataResponse
	(*AssertCanJoinRequest)(nil),              // 26: rooms.v1.AssertCanJoinRequest
	(*AssertCanJoinResponse)(nil),             // 27: rooms.v1.AssertCanJoinResponse
	(*RefreshJoinTokenRequest)(nil),           // 28: rooms.v1.RefreshJoinTokenRequest
	(*RefreshJoinTokenResponse)(nil),          // 29: rooms.v1.RefreshJoinTokenResponse
	(*GetTURNCredentialsRequest)(nil),         // 30: rooms.v1.GetTURNCredentialsRequest
	(*ICEServer)(nil),                         // 31: rooms.v1.ICEServer
	(*GetTURNCredentialsResponse)(nil),        // 32: rooms.v1.GetTURNCredentialsResponse
	(*Error)(nil),                             // 33: rooms.v1.Error
	(*Status)(nil),                            // 34: rooms.v1.Status
	(*timestamppb.Timestamp)(nil),             // 35: google.protobuf.Timestamp
}
var file_rooms_v1_rooms_proto_depIdxs = []int32{
	35, // 0: rooms.v1.Room.created_at:type_name -> google.protobuf.Timestamp
	35, // 1: rooms.v1.Room.updated_at:type_name -> google.protobuf.Timestamp
	35, // 2: rooms.v1.Room.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: rooms.v1.Room.room_settings:type_name -> rooms.v1.RoomSettings
	0,  // 4: rooms.v1.CreateRoomRequest.room_settings:type_name -> rooms.v1.RoomSettings
	1,  // 5: rooms.v1.CreateRoomResponse.room:type_name -> rooms.v1.Room
	1,  // 6: rooms.v1.GetRoomResponse.room:type_name -> rooms.v1.Room
	0,  // 7: rooms.v1.UpdateRoomRequest.room_settings:type_name -> rooms.v1.RoomSettings
	1,  // 8: rooms.v1.UpdateRoomResponse.room:type_name -> rooms.v1.Room
	1,  // 9: rooms.v1.ListRoomsResponse.rooms:type_name -> rooms.v1.Room
	35, // 10: rooms.v1.Participant.joined_at:type_name -> google.protobuf.Timestamp
	35, // 11: rooms.v1.Participant.left_at:type_name -> google.protobuf.Timestamp
	15, // 12: rooms.v1.Participant.metadata:type_name -> rooms.v1.ParticipantMetadata
	15, // 13: rooms.v1.AddParticipantRequest.metadata:type_name -> rooms.v1.ParticipantMetadata
	14, // 14: rooms.v1.AddParticipantResponse.participant:type_name -> rooms.v1.Participant
	14, // 15: rooms.v1.GetParticipantsResponse.participants:type_name -> rooms.v1.Participant
	14, // 16: rooms.v1.IsParticipantResponse.participant:type_name -> rooms.v1.Participant
	15, // 17: rooms.v1.UpdateParticipantMetadataRequest.metadata:type_name -> rooms.v1.ParticipantMetadata
	14, // 18: rooms.v1.UpdateParticipantMetadataResponse.participant:type_name -> rooms.v1.Participant
	31, // 19: rooms.v1.GetTURNCredentialsResponse.ice_servers:type_name -> rooms.v1.ICEServer
	33, // 20: rooms.v1.Status.error:type_name -> rooms.v1.Error
	2,  // 21: rooms.v1.RoomService.CreateRoom:input_type -> rooms.v1.CreateRoomRequest
	4,  // 22: rooms.v1.RoomService.GetRoom:input_type -> rooms.v1.GetRoomRequest
	6,  // 23: rooms.v1.RoomService.UpdateRoom:input_type -> rooms.v1.UpdateRoomRequest
	8,  // 24: rooms.v1.RoomService.DeleteRoom:input_type -> rooms.v1.DeleteRoomRequest
	10, // 25: rooms.v1.RoomService.ListRooms:input_type -> rooms.v1.ListRoomsRequest
	12, // 26: rooms.v1.RoomService.EndRoom:input_type -> rooms.v1.EndRoomRequest
	16, // 27: rooms.v1.RoomService.AddParticipant:input_type -> rooms.v1.AddParticipantRequest
	18, // 28: rooms.v1.RoomService.RemoveParticipant:input_type -> rooms.v1.RemoveParticipantRequest
	20, // 29: rooms.v1.RoomService.GetParticipants:input_type -> rooms.v1.GetParticipantsRequest
	22, // 30: rooms.v1.RoomService.IsParticipant:input_type -> rooms.v1.IsParticipantRequest
	24, // 31: rooms.v1.RoomService.UpdateParticipantMetadata:input_type -> rooms.v1.UpdateParticipantMetadataRequest
	26, // 32: rooms.v1.RoomService.AssertCanJoin:input_type -> rooms.v1.AssertCanJoinRequest
	28, // 33: rooms.v1.RoomService.RefreshJoinToken:input_type -> rooms.v1.RefreshJoinTokenRequest
	30, // 34: rooms.v1.RoomService.GetTURNCredentials:input_type -> rooms.v1.GetTURNCredentialsRequest
	3,  // 35: rooms.v1.RoomService.CreateRoom:output_type -> rooms.v1.CreateRoomResponse
	5,  // 36: rooms.v1.RoomService.GetRoom:output_type -> rooms.v1.GetRoomResponse
	7,  // 37: rooms.v1.RoomService.UpdateRoom:output_type -> rooms.v1.UpdateRoomResponse
	9,  // 38: rooms.v1.RoomService.DeleteRoom:output_type -> rooms.v1.DeleteRoomResponse
	11, // 39: rooms.v1.RoomService.ListRooms:output_type -> rooms.v1.ListRoomsResponse
	13, // 40: rooms.v1.RoomService.EndRoom:output_type -> rooms.v1.EndRoomResponse
	17, // 41: rooms.v1.RoomService.AddParticipant:output_type -> rooms.v1.AddParticipantResponse
	19, // 42: rooms.v1.RoomService.RemoveParticipant:output_type -> rooms.v1.RemoveParticipantResponse
	21, // 43: rooms.v1.RoomService.GetParticipants:output_type -> rooms.v1.GetParticipantsResponse
	23, // 44: rooms.v1.RoomService.IsParticipant:output_type -> rooms.v1.IsParticipantResponse
	25, // 45: rooms.v1.RoomService.UpdateParticipantMetadata:output_type -> rooms.v1.UpdateParticipantMetadataResponse
	27, // 46: rooms.v1.RoomService.AssertCanJoin:output_type -> rooms.v1.AssertCanJoinResponse
	29, // 47: rooms.v1.RoomService.RefreshJoinToken:output_type -> rooms.v1.RefreshJoinTokenResponse
	32, // 48: rooms.v1.RoomService.GetTURNCredentials:output_type -> rooms.v1.GetTURNCredentialsResponse
	35, // [35:49] is the sub-list for method output_type
	21, // [21:35] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_rooms_v1_rooms_proto_init() }
func file_rooms_v1_rooms_proto_init() {
	if File_rooms_v1_rooms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rooms_v1_rooms_proto_rawDesc), len(file_rooms_v1_rooms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rooms_v1_rooms_proto_goTypes,
		DependencyIndexes: file_rooms_v1_rooms_proto_depIdxs,
		MessageInfos:      file_rooms_v1_rooms_proto_msgTypes,
	}.Build()
	File_rooms_v1_rooms_proto = out.File
	file_rooms_v1_rooms_proto_goTypes = nil
	file_rooms_v1_rooms_proto_depIdxs = nil
}
